// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Assessment struct {
	ID          pgtype.UUID
	SchoolID    pgtype.UUID
	SubjectID   pgtype.UUID
	StudentID   pgtype.UUID
	TeacherID   pgtype.UUID
	Feedback    pgtype.Text
	SubmittedAt pgtype.Timestamp
	CreatedAt   pgtype.Timestamp
	UpdatedAt   pgtype.Timestamp
}

type AssessmentComponent struct {
	ID                pgtype.UUID
	AssessmentID      pgtype.UUID
	RubricComponentID pgtype.UUID
	Score             int32
	CreatedAt         pgtype.Timestamp
}

type JwtBlacklist struct {
	Jti       string
	ExpiresAt pgtype.Timestamp
	CreatedAt pgtype.Timestamp
}

type ParentStudent struct {
	ID        pgtype.UUID
	ParentID  pgtype.UUID
	StudentID pgtype.UUID
	CreatedAt pgtype.Timestamp
}

type Role struct {
	ID        pgtype.UUID
	Name      string
	CreatedAt pgtype.Timestamp
}

type RubricComponent struct {
	ID          pgtype.UUID
	SchoolID    pgtype.UUID
	SubjectID   pgtype.UUID
	Name        string
	Description pgtype.Text
	ScaleMin    pgtype.Int4
	ScaleMax    pgtype.Int4
	Weight      pgtype.Int4
	CreatedAt   pgtype.Timestamp
	UpdatedAt   pgtype.Timestamp
}

type School struct {
	ID        pgtype.UUID
	Name      string
	CreatedAt pgtype.Timestamp
	UpdatedAt pgtype.Timestamp
}

type Student struct {
	ID        pgtype.UUID
	SchoolID  pgtype.UUID
	UserID    pgtype.UUID
	Class     pgtype.Text
	CreatedAt pgtype.Timestamp
	UpdatedAt pgtype.Timestamp
}

type Subject struct {
	ID          pgtype.UUID
	SchoolID    pgtype.UUID
	Name        string
	Description pgtype.Text
	CreatedAt   pgtype.Timestamp
	UpdatedAt   pgtype.Timestamp
}

type User struct {
	ID           pgtype.UUID
	Email        string
	PasswordHash pgtype.Text
	Name         string
	CreatedAt    pgtype.Timestamp
	UpdatedAt    pgtype.Timestamp
	DeletedAt    pgtype.Timestamp
}

type UserRole struct {
	ID        pgtype.UUID
	UserID    pgtype.UUID
	RoleID    pgtype.UUID
	SchoolID  pgtype.UUID
	CreatedAt pgtype.Timestamp
}

type UserSchool struct {
	ID        pgtype.UUID
	UserID    pgtype.UUID
	SchoolID  pgtype.UUID
	CreatedAt pgtype.Timestamp
}
