// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const blacklistJWT = `-- name: BlacklistJWT :one
INSERT INTO jwt_blacklist (jti, expires_at)
VALUES ($1, $2) RETURNING jti, expires_at, created_at
`

type BlacklistJWTParams struct {
	Jti       string
	ExpiresAt pgtype.Timestamp
}

func (q *Queries) BlacklistJWT(ctx context.Context, arg BlacklistJWTParams) (JwtBlacklist, error) {
	row := q.db.QueryRow(ctx, blacklistJWT, arg.Jti, arg.ExpiresAt)
	var i JwtBlacklist
	err := row.Scan(&i.Jti, &i.ExpiresAt, &i.CreatedAt)
	return i, err
}

const countAssessmentsBySubject = `-- name: CountAssessmentsBySubject :one
SELECT COUNT(*) FROM assessments WHERE subject_id = $1
`

func (q *Queries) CountAssessmentsBySubject(ctx context.Context, subjectID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countAssessmentsBySubject, subjectID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAssessment = `-- name: CreateAssessment :one
INSERT INTO assessments (school_id, subject_id, student_id, teacher_id, feedback)
VALUES ($1, $2, $3, $4, $5) RETURNING id, school_id, subject_id, student_id, teacher_id, feedback, submitted_at, created_at, updated_at
`

type CreateAssessmentParams struct {
	SchoolID  pgtype.UUID
	SubjectID pgtype.UUID
	StudentID pgtype.UUID
	TeacherID pgtype.UUID
	Feedback  pgtype.Text
}

func (q *Queries) CreateAssessment(ctx context.Context, arg CreateAssessmentParams) (Assessment, error) {
	row := q.db.QueryRow(ctx, createAssessment,
		arg.SchoolID,
		arg.SubjectID,
		arg.StudentID,
		arg.TeacherID,
		arg.Feedback,
	)
	var i Assessment
	err := row.Scan(
		&i.ID,
		&i.SchoolID,
		&i.SubjectID,
		&i.StudentID,
		&i.TeacherID,
		&i.Feedback,
		&i.SubmittedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createAssessmentComponent = `-- name: CreateAssessmentComponent :one
INSERT INTO assessment_components (assessment_id, rubric_component_id, score)
VALUES ($1, $2, $3) RETURNING id, assessment_id, rubric_component_id, score, created_at
`

type CreateAssessmentComponentParams struct {
	AssessmentID      pgtype.UUID
	RubricComponentID pgtype.UUID
	Score             int32
}

func (q *Queries) CreateAssessmentComponent(ctx context.Context, arg CreateAssessmentComponentParams) (AssessmentComponent, error) {
	row := q.db.QueryRow(ctx, createAssessmentComponent, arg.AssessmentID, arg.RubricComponentID, arg.Score)
	var i AssessmentComponent
	err := row.Scan(
		&i.ID,
		&i.AssessmentID,
		&i.RubricComponentID,
		&i.Score,
		&i.CreatedAt,
	)
	return i, err
}

const createRubricComponent = `-- name: CreateRubricComponent :one
INSERT INTO rubric_components (school_id, subject_id, name, description, scale_min, scale_max, weight)
VALUES ($1, $2, $3, $4, $5, $6, $7) RETURNING id, school_id, subject_id, name, description, scale_min, scale_max, weight, created_at, updated_at
`

type CreateRubricComponentParams struct {
	SchoolID    pgtype.UUID
	SubjectID   pgtype.UUID
	Name        string
	Description pgtype.Text
	ScaleMin    pgtype.Int4
	ScaleMax    pgtype.Int4
	Weight      pgtype.Int4
}

func (q *Queries) CreateRubricComponent(ctx context.Context, arg CreateRubricComponentParams) (RubricComponent, error) {
	row := q.db.QueryRow(ctx, createRubricComponent,
		arg.SchoolID,
		arg.SubjectID,
		arg.Name,
		arg.Description,
		arg.ScaleMin,
		arg.ScaleMax,
		arg.Weight,
	)
	var i RubricComponent
	err := row.Scan(
		&i.ID,
		&i.SchoolID,
		&i.SubjectID,
		&i.Name,
		&i.Description,
		&i.ScaleMin,
		&i.ScaleMax,
		&i.Weight,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createSchool = `-- name: CreateSchool :one
INSERT INTO schools (name) VALUES ($1) RETURNING id, name, created_at, updated_at
`

func (q *Queries) CreateSchool(ctx context.Context, name string) (School, error) {
	row := q.db.QueryRow(ctx, createSchool, name)
	var i School
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createStudent = `-- name: CreateStudent :one
INSERT INTO students (school_id, user_id, class)
VALUES ($1, $2, $3) RETURNING id, school_id, user_id, class, created_at, updated_at
`

type CreateStudentParams struct {
	SchoolID pgtype.UUID
	UserID   pgtype.UUID
	Class    pgtype.Text
}

func (q *Queries) CreateStudent(ctx context.Context, arg CreateStudentParams) (Student, error) {
	row := q.db.QueryRow(ctx, createStudent, arg.SchoolID, arg.UserID, arg.Class)
	var i Student
	err := row.Scan(
		&i.ID,
		&i.SchoolID,
		&i.UserID,
		&i.Class,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createSubject = `-- name: CreateSubject :one
INSERT INTO subjects (school_id, name, description)
VALUES ($1, $2, $3) RETURNING id, school_id, name, description, created_at, updated_at
`

type CreateSubjectParams struct {
	SchoolID    pgtype.UUID
	Name        string
	Description pgtype.Text
}

func (q *Queries) CreateSubject(ctx context.Context, arg CreateSubjectParams) (Subject, error) {
	row := q.db.QueryRow(ctx, createSubject, arg.SchoolID, arg.Name, arg.Description)
	var i Subject
	err := row.Scan(
		&i.ID,
		&i.SchoolID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (email, password_hash, name)
VALUES ($1, $2, $3)
RETURNING id, email, password_hash, name, created_at, updated_at, deleted_at
`

type CreateUserParams struct {
	Email        string
	PasswordHash pgtype.Text
	Name         string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser, arg.Email, arg.PasswordHash, arg.Name)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const deleteAssessment = `-- name: DeleteAssessment :exec
DELETE FROM assessments WHERE id = $1
`

func (q *Queries) DeleteAssessment(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteAssessment, id)
	return err
}

const deleteAssessmentComponents = `-- name: DeleteAssessmentComponents :exec
DELETE FROM assessment_components WHERE assessment_id = $1
`

func (q *Queries) DeleteAssessmentComponents(ctx context.Context, assessmentID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteAssessmentComponents, assessmentID)
	return err
}

const deleteSubject = `-- name: DeleteSubject :exec
DELETE FROM subjects WHERE id = $1
`

func (q *Queries) DeleteSubject(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteSubject, id)
	return err
}

const getAssessmentByID = `-- name: GetAssessmentByID :one
SELECT id, school_id, subject_id, student_id, teacher_id, feedback, submitted_at, created_at, updated_at FROM assessments WHERE id = $1
`

func (q *Queries) GetAssessmentByID(ctx context.Context, id pgtype.UUID) (Assessment, error) {
	row := q.db.QueryRow(ctx, getAssessmentByID, id)
	var i Assessment
	err := row.Scan(
		&i.ID,
		&i.SchoolID,
		&i.SubjectID,
		&i.StudentID,
		&i.TeacherID,
		&i.Feedback,
		&i.SubmittedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAssessmentComponents = `-- name: GetAssessmentComponents :many
SELECT id, assessment_id, rubric_component_id, score, created_at FROM assessment_components WHERE assessment_id = $1
`

func (q *Queries) GetAssessmentComponents(ctx context.Context, assessmentID pgtype.UUID) ([]AssessmentComponent, error) {
	rows, err := q.db.Query(ctx, getAssessmentComponents, assessmentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AssessmentComponent
	for rows.Next() {
		var i AssessmentComponent
		if err := rows.Scan(
			&i.ID,
			&i.AssessmentID,
			&i.RubricComponentID,
			&i.Score,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAssessmentsBySchool = `-- name: GetAssessmentsBySchool :many
SELECT id, school_id, subject_id, student_id, teacher_id, feedback, submitted_at, created_at, updated_at FROM assessments WHERE school_id = $1 ORDER BY submitted_at DESC
`

func (q *Queries) GetAssessmentsBySchool(ctx context.Context, schoolID pgtype.UUID) ([]Assessment, error) {
	rows, err := q.db.Query(ctx, getAssessmentsBySchool, schoolID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Assessment
	for rows.Next() {
		var i Assessment
		if err := rows.Scan(
			&i.ID,
			&i.SchoolID,
			&i.SubjectID,
			&i.StudentID,
			&i.TeacherID,
			&i.Feedback,
			&i.SubmittedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAssessmentsByStudent = `-- name: GetAssessmentsByStudent :many
SELECT id, school_id, subject_id, student_id, teacher_id, feedback, submitted_at, created_at, updated_at FROM assessments WHERE student_id = $1 ORDER BY submitted_at DESC
`

func (q *Queries) GetAssessmentsByStudent(ctx context.Context, studentID pgtype.UUID) ([]Assessment, error) {
	rows, err := q.db.Query(ctx, getAssessmentsByStudent, studentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Assessment
	for rows.Next() {
		var i Assessment
		if err := rows.Scan(
			&i.ID,
			&i.SchoolID,
			&i.SubjectID,
			&i.StudentID,
			&i.TeacherID,
			&i.Feedback,
			&i.SubmittedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRubricComponentByID = `-- name: GetRubricComponentByID :one
SELECT id, school_id, subject_id, name, description, scale_min, scale_max, weight, created_at, updated_at FROM rubric_components WHERE id = $1
`

func (q *Queries) GetRubricComponentByID(ctx context.Context, id pgtype.UUID) (RubricComponent, error) {
	row := q.db.QueryRow(ctx, getRubricComponentByID, id)
	var i RubricComponent
	err := row.Scan(
		&i.ID,
		&i.SchoolID,
		&i.SubjectID,
		&i.Name,
		&i.Description,
		&i.ScaleMin,
		&i.ScaleMax,
		&i.Weight,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRubricComponentsBySubject = `-- name: GetRubricComponentsBySubject :many
SELECT id, school_id, subject_id, name, description, scale_min, scale_max, weight, created_at, updated_at FROM rubric_components WHERE subject_id = $1 ORDER BY name
`

func (q *Queries) GetRubricComponentsBySubject(ctx context.Context, subjectID pgtype.UUID) ([]RubricComponent, error) {
	rows, err := q.db.Query(ctx, getRubricComponentsBySubject, subjectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RubricComponent
	for rows.Next() {
		var i RubricComponent
		if err := rows.Scan(
			&i.ID,
			&i.SchoolID,
			&i.SubjectID,
			&i.Name,
			&i.Description,
			&i.ScaleMin,
			&i.ScaleMax,
			&i.Weight,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSchool = `-- name: GetSchool :one
SELECT id, name, created_at, updated_at FROM schools WHERE id = $1
`

func (q *Queries) GetSchool(ctx context.Context, id pgtype.UUID) (School, error) {
	row := q.db.QueryRow(ctx, getSchool, id)
	var i School
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getStudentByID = `-- name: GetStudentByID :one
SELECT id, school_id, user_id, class, created_at, updated_at FROM students WHERE id = $1
`

func (q *Queries) GetStudentByID(ctx context.Context, id pgtype.UUID) (Student, error) {
	row := q.db.QueryRow(ctx, getStudentByID, id)
	var i Student
	err := row.Scan(
		&i.ID,
		&i.SchoolID,
		&i.UserID,
		&i.Class,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getStudentsBySchool = `-- name: GetStudentsBySchool :many
SELECT id, school_id, user_id, class, created_at, updated_at FROM students WHERE school_id = $1 ORDER BY created_at
`

func (q *Queries) GetStudentsBySchool(ctx context.Context, schoolID pgtype.UUID) ([]Student, error) {
	rows, err := q.db.Query(ctx, getStudentsBySchool, schoolID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Student
	for rows.Next() {
		var i Student
		if err := rows.Scan(
			&i.ID,
			&i.SchoolID,
			&i.UserID,
			&i.Class,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSubjectByID = `-- name: GetSubjectByID :one
SELECT id, school_id, name, description, created_at, updated_at FROM subjects WHERE id = $1
`

func (q *Queries) GetSubjectByID(ctx context.Context, id pgtype.UUID) (Subject, error) {
	row := q.db.QueryRow(ctx, getSubjectByID, id)
	var i Subject
	err := row.Scan(
		&i.ID,
		&i.SchoolID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSubjectsBySchool = `-- name: GetSubjectsBySchool :many
SELECT id, school_id, name, description, created_at, updated_at FROM subjects WHERE school_id = $1 ORDER BY name
`

func (q *Queries) GetSubjectsBySchool(ctx context.Context, schoolID pgtype.UUID) ([]Subject, error) {
	rows, err := q.db.Query(ctx, getSubjectsBySchool, schoolID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Subject
	for rows.Next() {
		var i Subject
		if err := rows.Scan(
			&i.ID,
			&i.SchoolID,
			&i.Name,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, password_hash, name, created_at, updated_at, deleted_at FROM users WHERE email = $1 AND deleted_at IS NULL
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, password_hash, name, created_at, updated_at, deleted_at FROM users WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetUserByID(ctx context.Context, id pgtype.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getUserRoles = `-- name: GetUserRoles :many
SELECT role_id FROM user_roles WHERE user_id = $1
`

func (q *Queries) GetUserRoles(ctx context.Context, userID pgtype.UUID) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, getUserRoles, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []pgtype.UUID
	for rows.Next() {
		var role_id pgtype.UUID
		if err := rows.Scan(&role_id); err != nil {
			return nil, err
		}
		items = append(items, role_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserSchools = `-- name: GetUserSchools :many
SELECT school_id FROM user_schools WHERE user_id = $1
`

func (q *Queries) GetUserSchools(ctx context.Context, userID pgtype.UUID) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, getUserSchools, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []pgtype.UUID
	for rows.Next() {
		var school_id pgtype.UUID
		if err := rows.Scan(&school_id); err != nil {
			return nil, err
		}
		items = append(items, school_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const isJWTBlacklisted = `-- name: IsJWTBlacklisted :one
SELECT jti FROM jwt_blacklist WHERE jti = $1
`

func (q *Queries) IsJWTBlacklisted(ctx context.Context, jti string) (string, error) {
	row := q.db.QueryRow(ctx, isJWTBlacklisted, jti)
	var jti_2 string
	err := row.Scan(&jti_2)
	return jti_2, err
}

const updateAssessment = `-- name: UpdateAssessment :exec
UPDATE assessments SET feedback = $2, updated_at = NOW() WHERE id = $1
`

type UpdateAssessmentParams struct {
	ID       pgtype.UUID
	Feedback pgtype.Text
}

func (q *Queries) UpdateAssessment(ctx context.Context, arg UpdateAssessmentParams) error {
	_, err := q.db.Exec(ctx, updateAssessment, arg.ID, arg.Feedback)
	return err
}
